- hosts: localhost
  connection: local
  become: true
 
  pre_tasks:
    - name: hack to resolve Problem with MergeList Issue
      become: true
      shell: 'find /var/lib/apt/lists -maxdepth 1 -type f -exec rm -v {} \;'
    - name: update repositories
      apt:
        update_cache: yes
        autoremove: yes
      changed_when: true

  tasks:
    #- include: tasks/init.yml
    - include: tasks/iot.yml
    #- include: tasks/gcc.yml
    #- include: tasks/ffmpeg.yml #Requires testing with cameras
    