- include_vars: tasks/vars.yml



- name: Start MQTT
  become: yes
  command: node cloudiot_mqtt_example_nodejs.js \
    mqttDeviceDemo \
    --projectId={{ project_id }} \
    --cloudRegion={{ region }} \
    --registryId={{ registry }} \
    --deviceId=jetson-01 \
    --privateKeyFile=/home/jetson/rsa_private_gcs.pem \
    --numMessages=25 \
    --serverCertFile=roots.pem \
    --algorithm=RS256
  args: 
    chdir: /home/jetson/GCS-IOT

#- name: Token Refresh