- include_vars: tasks/vars.yml
- name: IP Forward set
  become: true
  command: sysctl -w net.ipv4.ip_forward=1

- name: Network Config
  shell: printf
    'auto eth0\n
      iface eth0 inet static\n
      address {{ ip }}\n
      netmask 255.255.255.0\n
      gateway {{ gateway }}\n
      \n
    auto eth0:0\n
      iface eth0:0 inet static\n
      address {{ int_ip }}\n
      netmask 255.255.255.0' >> /etc/network/interfaces

- name: ifup
  become: true
  command: ifup eth0:0

- name: Installing packages
  become: true
  apt:
    update_cache: yes
    name:
      - htop
      - mc
      - python-pexpect
      - nodejs
      - npm
      - apt-utils
      - ntpdate
      - ffmpeg

- name: set ntp 
  become: true
  command: ntpdate -u hu.pool.ntp.org

- name: Writing to ntp.conf
  shell: printf 
    'server 0.hu.pool.ntp.org
    server 1.hu.pool.ntp.org
    server 2.hu.pool.ntp.org
    server 3.hu.pool.ntp.org' >> /etc/ntp.conf

