- include_vars: tasks/vars.yml
- name: IP Forward set
  become: true
  command: sysctl -w net.ipv4.ip_forward=1

- name: Network Config
  shell: printf
    'auto eth0\n
      iface eth0 inet static\n
      address {{ ip }}\n
      netmask 255.255.255.0\n
      gateway {{ gateway }}\n
      \n
    auto eth0:0\n
      iface eth0:0 inet static\n
      address {{ int_ip }}\n
      netmask 255.255.255.0' >> /etc/network/interfaces

- name: ifup
  become: true
  command: ifup eth0:0


- name: DNS config
  become: true
  shell: printf 'nameserver 8.8.8.8' >> /etc/resolv.conf