- include_vars: tasks/vars.yml



- name: Installing NodeJS ... 
  become: true
  shell: curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -

- name: Installing NodeJS ... ...
  become: yes
  apt:
    update_cache: yes
    name:
      - nodejs
      - npm

- name: Clone IOT node
  git: 
    repo: 'https://devops:uNg5lieh@stash.sed.hu/scm/poc/google-iot-node-mqtt.git'
    dest: /home/jetson/GCS-IOT
    clone: yes
    update: yes 

- name: Install IOT node
  become: yes
  command: npm install
  args:
    chdir: /home/jetson/GCS-IOT

- name: GCS Keypair 
  become:  yes
  command: openssl req -x509 -newkey rsa:2048 -keyout /home/jetson/rsa_private_gcs.pem -nodes -out /home/jetson/rsa_cert_gcs.pem -subj "/CN=unused"

- name: Router Keypair
  become: yes
  command: openssl req -x509 -newkey rsa:2048 -keyout /home/jetson/rsa_private_mtk.pem -nodes -out /home/jetson/rsa_cert_mtk.pem -subj "/CN=unused"

- name: Register the key on GCS
  become: yes
  command: gcloud iot devices create jetson-01 --project={{ project_id }} --region={{ region }} --registry={{ registry }} --public-key path=/home/jetson/rsa_cert_gcs.pem,type=rsa-x509-pem

- name: Start MQTT
  become: yes
  command: nohup node cloudiot_mqtt_example_nodejs.js \
    mqttDeviceDemo \
    --projectId={{ project_id }} \
    --cloudRegion={{ region }} \
    --registryId={{ registry }} \
    --deviceId=jetson-01 \
    --privateKeyFile=/home/jetson/rsa_private_gcs.pem \
    --numMessages=25 \
    --serverCertFile=roots.pem \
    --algorithm=RS256 
  async: 45
  poll: 0
  args: 
    chdir: /home/jetson/GCS-IOT