- include_vars: tasks/vars.yml
- name: Installing Cloud SDK
  become: yes
  shell: echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list

- name: Required packages
  become: yes
  apt:
    name:
      - ca-certificates
      - gnupg
      - curl 

- name: Installing Cloud SDK ...
  become: yes
  shell: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
  #shell: curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  
- name: Installing Cloud SDK ... ... ...
  become: yes
  
  apt:
    update_cache: true
    name: google-cloud-sdk
    

- name: Clone IOT node
  git: 
    repo: 'https://devops:uNg5lieh@stash.sed.hu/scm/poc/google-iot-node-mqtt.git'
    dest: /home/jetson/GCS-IOT
    clone: yes
    update: yes 

- name: Install IOT node
  npm:
    path: /home/jetson/GCS-IOT

- name: GCS Keypair 
  become:  yes
  command: openssl req -x509 -newkey rsa:2048 -keyout rsa_private_gcs.pem -nodes -out rsa_cert_gcs.pem -subj "/CN=unused"

- name: Router Keypair
  become: yes
  command: openssl req -x509 -newkey rsa:2048 -keyout rsa_private_mtk.pem -nodes -out rsa_cert_mtk.pem -subj "/CN=unused"

- name: Initialize gcloud
  become: yes
  command: gcloud auth activate-service-account --key-file = /home/jetson/lit_creds.json

- name: Register the key on GCS
  become: yes
  command: gcloud iot devices create jetson-01 --project={{ project_id }} --region={{ region }} --registry={{ registry }} --public-key path=/home/jetson/rsa_cert_gcs.pem,type=rsa-x509-pem

- name: Start MQTT
  become: yes
  command: node cloudiot_mqtt_example_nodejs.js \
    mqttDeviceDemo \
    --projectId={{ project_id }} \
    --cloudRegion={{ region }} \
    --registryId={{ registry }} \
    --deviceId=jetson-01 \
    --privateKeyFile=/home/jetson/rsa_private_gcs.pem \
    --numMessages=25 \
    --algorithm=rsa-x509
  args: 
    chdir: /home/jetson/GCS-IOT

#- name: Token Refresh
