- include_vars: tasks/vars.yml

- name: Creating an empty file for interfaces
  become: true
  file:
    path: "/home/jetson/interfaces"
    state: touch

- name: Network Config
  shell: printf
    'auto eth0\n
      iface eth0 inet static\n
      address {{ ip }}\n
      netmask 255.255.255.0\n
      gateway {{ gateway }}\n
      \n
    auto eth0:0\n
      iface eth0:0 inet static\n
      address {{ int_ip }}\n
      netmask 255.255.255.0' >> /home/jetson/interfaces



- name: Copy a new "ntp.conf" file into place, backing up the original if it differs from the copied version
  become: true
  copy:
    src: /home/jetosn/interfaces
    dest: /etc/network/interfaces
    mode: '0644'
    backup: yes

- name: Remove file (delete file)
  become: true
  file:
    path: /home/jetson/interfaces
    state: absent